apiVersion: v1
kind: Service
metadata:
  name: es
  labels:
    component: es
spec:
  type: LoadBalancer
  #clusterIP: None
  selector:
    component: es
  ports:
  - name: http
    port: 9200
    protocol: TCP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: es
  labels:
    component: es
spec:
  replicas: 1
  selector:
    matchLabels:
      component: es
  serviceName: es
  template:
    metadata:
      labels:
        component: es
    spec:
      initContainers:
      - name: init-sysctl1
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
      - name: init-sysctl2
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ["sysctl", "-w", "vm.swappiness=1"]
        securityContext:
          privileged: true
      containers:
      - name: es
        securityContext:
          capabilities:
            add:
            - IPC_LOCK
        image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: cluster.name
          value: mycluster
        - name: cluster.initial_master_nodes
          value: es-0
        ports:
        - containerPort: 9200
          name: http
          protocol: TCP
