apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    component: mongodb
spec:
  clusterIP: None
  selector:
    component: mongodb
  ports:
  - port: 27017
    targetPort: 27017
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  labels:
    component: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      component: mongodb
  serviceName: mongodb
  template:
    metadata:
      labels:
        component: mongodb
    spec:
      containers:
      - name: mongod-node-a
        image: mongo:5.0.14
        command:
        - mongod
        - "--bind_ip"
        - "0.0.0.0"
        - "--port"
        - "27017"
        ports:
        - containerPort: 27017