apiVersion: v1
kind: Service
metadata:
  name: ui
  labels:
    component: ui
spec:
  type: LoadBalancer
  selector:
    component: ui
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ui
  labels:
    component: ui
spec:
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      component: ui
  serviceName: ui
  template:
    metadata:
      labels:
        component: ui
    spec:
      containers:
      - name: ui
        image: docker.io/cloudcms/ui-server:3.2.84
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        envFrom:
        - secretRef:
            name: gitana-env
        env:
        - name: GITANA_API_URL
          value: "http://api.default.svc.cluster.local:8080"
        - name: CLOUDCMS_NOTIFICATIONS_ENABLED
          value: "true"
        - name: CLOUDCMS_NOTIFICATIONS_STOMP_HOST
          value: "activemq.default.svc.cluster.local"
        - name: CLOUDCMS_NOTIFICATIONS_STOMP_PORT
          value: "61613"
        - name: CLOUDCMS_NOTIFICATIONS_STOMP_QUEUE_URL
          value: "/queue/cloudcms.ui.queue"
        volumeMounts:
        - name: hosts
          mountPath: "/hosts"
      volumes:
      - name: hosts
        emptyDir: {}
      imagePullSecrets:
      - name: dev-registry
        